// This file is automatically generated. Do not edit.
export const firebaseConfig = {
  projectId: "ranoro-jm8l0",
  appId: "1:290934350177:web:2365c77eaca4bb0d906520",
  storageBucket: "ranoro-jm8l0.appspot.com",
  apiKey: "AIzaSyA_ot6L0zgglc1tC0BounxYIvj7y8048Sg",
  authDomain: "ranoro-jm8l0.firebaseapp.com",
  messagingSenderId: "290934350177",
};
