
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `(function(){
  try{
    var s = localStorage.getItem('theme');
    var m = window.matchMedia('(prefers-color-scheme: dark)').matches;
    var t = (s === 'dark') || (!s || s === 'system') && m ? 'dark' : 'light';
    var d = document.documentElement;
    if(t==='dark') d.classList.add('dark'); else d.classList.remove('dark');
    d.setAttribute('data-theme', t);
  }catch(e){}
})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
       <head>
        {/* The script is removed as ThemeProvider is no longer global */}
      </head>
      <body className={inter.className}>
          {children}
        </body>
    </html>
  );
}
